name: CI
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/rubocop@ruby-2.4
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
  bundler_audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@ruby-2.4
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/eslint@v1
      with:
        args: '**/*.js'

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:admin
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:core
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:storefront
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}

  plugins_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:plugins
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
